### ISSUE TITLE
How does multicam_calibration compare to Kalibr?

### ISSUE THREAD

**Issue by chutsu** [KumarRobotics/multicam_calibration#1]
Just out of curiosity what is the motivation behind this repo? Are you planning to be a better multi-camera calibration than Kalibr? If so have you done comparisons?

**Comment by kartikmohta** [comment]
This was made after being slightly frustrated by the speed of camera-camera calibration using Kalibr. It can take up to 10 mins for Kalibr to finish the camera-camera calibration. Our tool is definitely not as feature rich as Kalibr but by simplifying the tool we are able to speed it up a lot. On any modern laptop, the calibration tool can be run with a camera rate of  between 5-10Hz without requiring any bag file collection and the actual optimization after data collection takes less than 30 secs, mostly less than 10 secs.

**Comment by chutsu** [comment]
Nice thanks. I'll try it out sometime :)
