### ISSUE TITLE
which algorithm is used in this repo?

### ISSUE THREAD

**Issue by cbenitez81** [KumarRobotics/multicam_calibration#4]
Thanks for posting the code. I was wondering which algorithm is implemented. There is anyway to infer the graph of cameras or input the graph a constrains?.

Thanks

**Comment by berndpfrommer** [comment]
The algorithm is nothing special, just minimizing the reprojection error (Huber norm) with Ceres. Yes, the camera poses are optimizer variables but they are just not printed out.
Entering constraints to the graph is not so easy though. That would be easier to implement had we used a graph based optimizer like GTSAM.
