### ISSUE TITLE
ROS Noetic support

### ISSUE THREAD

**Issue by fcladera** [KumarRobotics/multicam_calibration#5]
`multicam_calibration` seems to be failing on Noetic:

```
Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 1.557614e-13 <= 1.000000e-12)

[ INFO] [1627162181.284741213]: writing calibration to /home/dcist/autonomy-ws/src/autonomy_stack/calibration/multicam_calibration/calib/example/./ovc-2021-07-24-17-29-41.yaml
[ERROR] [1627162181.294380799]: Exception thrown while processing service call: OpenCV(4.2.0) ../modules/core/src/matmul.dispatch.cpp:337: error: (-215:Assertion failed) type == B.type() in function 'gemm'
```

I'll try to fix it, but if you have any clues it would be greatly appreciated.

Thanks!!

**Comment by berndpfrommer** [comment]
Hmm. I thought I had run it on noetic before. I assume you are running Ubuntu 20.04. Can you upload the yaml files and the bag to e.g. google drive?

**Comment by fcladera** [comment]
I confirm that it is an issue on our side. Let me take a look into our yaml.

**Comment by berndpfrommer** [comment]
There rarely is an issue on your side that nobody else will hit. The error message certainly doesn't point straightforwardly to what's wrong. So if you an just add briefly what caused the problem, even if (and particularly if) it's somewhat embarrassing, that would be great :)

**Comment by fcladera** [comment]
Yes, sorry! I will update this issue once we get access to the quad tomorrow :+1: Thanks for your help @berndpfrommer!

**Comment by fcladera** [comment]
Confirmed that it works well in noetic. See #6 if you face this error.
