### ISSUE TITLE
Handling unsynchronized cameras

### ISSUE THREAD

**Issue by oleg-alexandrov** [KumarRobotics/multicam_calibration#7]
I am curious how this multi-camera package handles the fact that the acquisition times of the two cameras may not be identical (or may not even have the same frequency). Does it do some kind of time interpolation for the poses? Or it is assumed that the the calibration target moves slowly enough that interpolation is not necessary?

**Comment by berndpfrommer** [comment]
No sophistication here ... if the images are unsynchronized things get ugly. You can run it with the use_approximate_sync flag (see launch file) which will use the ROS built-in sync to find images from each camera that are close in time. Meaning: if your calibration board moves fast the time lags between the shutters closing are going to mess up the calibration. Of course that's always a matter of degree. So: bright light, short shutter times, high image frequency and slow board motion is the best you can do if you cannot hardware sync the cameras.

**Comment by oleg-alexandrov** [comment]
Likely approx sync is good enough most of the time. Thank you for your response.  I will close this issue as resolved.
